import { Movie } from './types';

export const movies: Movie[] = [
  {
    id: 'stranger-things',
    title: 'Stranger Things',
    overview: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
    backdropUrl: 'https://images.unsplash.com/photo-1574375927938-d5a98e8edd85?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1574375927938-d5a98e8edd85?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    rating: 'TV-14',
    duration: '4 Seasons',
    releaseYear: 2022,
    genres: ['Sci-Fi', 'Horror', 'Drama'],
    cast: ['Winona Ryder', 'David Harbour', 'Millie Bobby Brown', 'Finn Wolfhard'],
    matchScore: 98,
    isTrending: true,
    isPopular: true,
  },
  {
    id: 'neon-cyberpunk',
    title: 'Neo-City: Cyberpunk',
    overview: 'In a dystopian metropolis ruled by mega-corporations, a cybernetically enhanced street kid fights against corrupt corporate giants and black-market syndicates to survive.',
    backdropUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    rating: 'TV-MA',
    duration: '10 Episodes',
    releaseYear: 2023,
    genres: ['Anime', 'Sci-Fi', 'Action'],
    cast: ['Aoi Yuki', 'Kenjiro Tsuda', 'Hiroshi Kamiya'],
    matchScore: 96,
    isTrending: true,
    isPopular: false,
  },
  {
    id: 'stellar-odyssey',
    title: 'Stellar Odyssey',
    overview: 'A group of astronauts travel into a newly discovered wormhole in search of a new habitable home for mankind when Earth is struck by terminal ecological decay.',
    backdropUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    rating: 'PG-13',
    duration: '2h 45m',
    releaseYear: 2014,
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    matchScore: 99,
    isTrending: false,
    isPopular: true,
  },
  {
    id: 'our-blue-planet',
    title: 'Our Blue Planet',
    overview: 'Witness the planet\'s breathtaking natural systems up close, and explore how all living organisms are deeply interconnected inside this ground-breaking nature series.',
    backdropUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    rating: 'G',
    duration: '8 Episodes',
    releaseYear: 2021,
    genres: ['Nature & Science', 'Documentary'],
    cast: ['David Attenborough'],
    matchScore: 95,
    isTrending: true,
    isKids: true,
    isPopular: true,
  },
  {
    id: 'mystic-nebula',
    title: 'The Mystic Nebula',
    overview: 'Deep space exploration ships trigger an ancient sleeping bio-weapon in a distant hyper-cluster, threatening galactic civilizations in a war of visual wonders and mental control.',
    backdropUrl: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    rating: 'TV-14',
    duration: '1h 55m',
    releaseYear: 2025,
    genres: ['Sci-Fi', 'Action', 'Mystery'],
    cast: ['Zoe Saldana', 'Chris Pratt', 'Sigourney Weaver'],
    matchScore: 92,
    isTrending: false,
    isPopular: true,
  },
  {
    id: 'culinary-mastery',
    title: 'Culinary Mastery',
    overview: 'Embark on a culinary globetrotting tour with six of the world\'s most innovative Michelin chefs as they redefine standard flavor profiles, fine-dining structures, and traditional recipes.',
    backdropUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    rating: 'G',
    duration: '6 Episodes',
    releaseYear: 2024,
    genres: ['Lifestyle', 'Documentary', 'Food'],
    cast: ['Massimo Bottura', 'Dominique Crenn', 'Virgilio Martinez'],
    matchScore: 94,
    isTrending: true,
    isKids: true,
    isPopular: false,
  },
  {
    id: 'apex-hunter',
    title: 'Apex Hunter',
    overview: 'A rogue counter-terrorism officer on suspension must form an uneasy alliance with a black-ops assassin to locate a digital warhead capable of hijacking sovereign missile silos.',
    backdropUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    rating: 'R',
    duration: '2h 10m',
    releaseYear: 2025,
    genres: ['Action', 'Thriller'],
    cast: ['Idris Elba', 'Charlize Theron', 'Tom Hardy'],
    matchScore: 97,
    isTrending: true,
    isPopular: true,
  },
  {
    id: 'animated-dream',
    title: 'The Animated Dream',
    overview: 'A whimsical and magical story of an enchanted wood-gatherer who discovers a luminous fairy princess hidden inside a glowing golden bamboo stalk.',
    backdropUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    rating: 'G',
    duration: '1h 38m',
    releaseYear: 1997,
    genres: ['Kids & Family', 'Anime', 'Fantasy'],
    cast: ['Rumi Hiiragi', 'Miyu Irino'],
    matchScore: 93,
    isTrending: false,
    isKids: true,
    isPopular: false,
  },
  {
    id: 'circuit-breakers',
    title: 'Circuit Breakers',
    overview: 'An underground hacking group leverages artificial dreaming technology to orchestrate the most lucrative bank heist in history, but reality and fantasy immediately begins to fracture.',
    backdropUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    rating: 'TV-MA',
    duration: '2h 15m',
    releaseYear: 2026,
    genres: ['Sci-Fi', 'Thriller', 'Mystery'],
    cast: ['Rami Malek', 'Keanu Reeves', 'Carrie-Anne Moss'],
    matchScore: 98,
    isTrending: true,
    isPopular: true,
  },
  {
    id: 'redline-syndicate',
    title: 'Redline Syndicate',
    overview: 'An elite heist driver finds himself blackmailed by a ruthless underworld boss into executing back-to-back high-speed operations across major European capitals.',
    backdropUrl: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    rating: 'R',
    duration: '1h 58m',
    releaseYear: 2024,
    genres: ['Action', 'Thriller', 'Crime'],
    cast: ['Jason Statham', 'Michelle Rodriguez', 'Pedro Pascal'],
    matchScore: 95,
    isTrending: true,
    isPopular: true,
  },
  {
    id: 'mach-overdrive',
    title: 'Mach 1: Overdrive',
    overview: 'Adrenaline peaks on the world speedway as a talented but reckless rookie driver attempts to challenge a three-time champion for the Formula-Overdrive crown.',
    backdropUrl: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    rating: 'PG-13',
    duration: '2h 05m',
    releaseYear: 2025,
    genres: ['Action', 'Sports'],
    cast: ['Michael B. Jordan', 'Florence Pugh', 'Lewis Hamilton'],
    matchScore: 92,
    isTrending: true,
    isPopular: false,
  },
  {
    id: 'wet-street-detective',
    title: 'The Wet Street Detective',
    overview: 'A cynical detective in a permanently rain-slicked neon metropolis unpicks the thread of a bizarre string of assassinations connected to high-ranking municipal officials.',
    backdropUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    rating: 'TV-MA',
    duration: '2 Seasons',
    releaseYear: 2023,
    genres: ['Thriller', 'Mystery', 'Drama'],
    cast: ['Cillian Murphy', 'Ana de Armas', 'Jeffrey Wright'],
    matchScore: 89,
    isTrending: false,
    isPopular: true,
  },
  {
    id: 'crown-elidon',
    title: 'Crown of Elidon',
    overview: 'An ancient relic of absolute royal authority is stolen from the high vaults of Elidon, triggering a multi-faction search across dangerous, magical fantasy realms.',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    rating: 'PG-13',
    duration: '2h 32m',
    releaseYear: 2024,
    genres: ['Fantasy', 'Adventure', 'Action'],
    cast: ['Timothée Chalamet', 'Zendaya', 'Ian McKellen'],
    matchScore: 91,
    isTrending: false,
    isPopular: true,
  },
  {
    id: 'deep-oceanic',
    title: 'Deep Oceanic Odyssey',
    overview: 'Descend into the absolute depths of the Earth\'s least explored ocean trenches to witness biological phenomena and mesmerizing marine creatures never before captured on camera.',
    backdropUrl: 'https://images.unsplash.com/photo-1551244072-5d12893278ab?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551244072-5d12893278ab?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    rating: 'G',
    duration: '6 Episodes',
    releaseYear: 2025,
    genres: ['Nature & Science', 'Documentary'],
    cast: ['Sigourney Weaver', 'Sylvia Earle'],
    matchScore: 97,
    isTrending: true,
    isKids: true,
    isPopular: true,
  },
  {
    id: 'whispering-woods',
    title: 'Whispering Woods',
    overview: 'A team of land surveyors map an old-growth national forest and encounter supernatural anomalies that play upon their deepest personal psychological fears, slowly turning them against one another.',
    backdropUrl: 'https://images.unsplash.com/photo-1505635552518-3448ff116af3?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1505635552518-3448ff116af3?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    rating: 'R',
    duration: '1h 48m',
    releaseYear: 2023,
    genres: ['Horror', 'Thriller', 'Mystery'],
    cast: ['Lupita Nyong\'o', 'Winston Duke', 'Elisabeth Moss'],
    matchScore: 88,
    isTrending: false,
    isPopular: false,
  },
  {
    id: 'house-shadows',
    title: 'House of Shadows',
    overview: 'An architect inherits a family estate with a rich historical past, only to discover the mansion\'s physical walls move and shift based on the emotional states of its inhabitants.',
    backdropUrl: 'https://images.unsplash.com/photo-1518621815164-613330573902?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518621815164-613330573902?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    rating: 'TV-MA',
    duration: '1h 52m',
    releaseYear: 2024,
    genres: ['Horror', 'Drama'],
    cast: ['Victoria Pedretti', 'Oliver Jackson-Cohen', 'Carla Gugino'],
    matchScore: 94,
    isTrending: false,
    isPopular: true,
  },
  {
    id: 'cerebral-code',
    title: 'Cerebral Code',
    overview: 'A cybersecurity master-hacker discovers a digital pattern inside corporate server clouds that can project custom dreams straight into sleep-habits, but standard dream cycles begin to shatter.',
    backdropUrl: 'https://images.unsplash.com/photo-1549923746-c502d488f3aa?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1549923746-c502d488f3aa?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    rating: 'TV-MA',
    duration: '10 Episodes',
    releaseYear: 2026,
    genres: ['Sci-Fi', 'Thriller', 'Action'],
    cast: ['Rami Malek', 'Angela Bassett', 'Gemma Chan'],
    matchScore: 96,
    isTrending: true,
    isPopular: true,
  },
  {
    id: 'bistro-romance',
    title: 'Bistro Romance',
    overview: 'A passionate pastry chef and a Michelin-starred critic clash over recipe traditions in a cozy coastal French town, only to spark an unexpected romance amidst culinary rivalries.',
    backdropUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    rating: 'PG',
    duration: '1h 44m',
    releaseYear: 2025,
    genres: ['Comedy', 'Romance', 'Drama'],
    cast: ['Emma Stone', 'Lucas Bravo', 'Jean Reno'],
    matchScore: 90,
    isTrending: false,
    isPopular: false,
  },
  {
    id: 'lost-transit',
    title: 'Lost in Transit',
    overview: 'An ordinary flight turns into an extraordinary globe-spanning wild goose chase when a quirky family gets their luggage and boarding passes accidentally swapped with a secret agent.',
    backdropUrl: 'https://images.unsplash.com/photo-1488085061387-422e29b40080?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1488085061387-422e29b40080?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    rating: 'G',
    duration: '1h 50m',
    releaseYear: 2024,
    genres: ['Comedy', 'Adventure', 'Family'],
    cast: ['Steve Carell', 'Kathryn Hahn', 'Jack Black'],
    matchScore: 91,
    isTrending: false,
    isKids: true,
    isPopular: true,
  },
  {
    id: 'leaves-whisper',
    title: 'When Leaves Whisper',
    overview: 'Spanning three decades, this sweeping romantic drama charts the delicate choices of two childhood lovers who find their paths constantly crossing and separating through tectonic societal changes.',
    backdropUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    rating: 'PG-13',
    duration: '2h 12m',
    releaseYear: 2022,
    genres: ['Drama', 'Romance'],
    cast: ['Saoirse Ronan', 'Timothée Chalamet', 'Paul Mescal'],
    matchScore: 87,
    isTrending: false,
    isPopular: false,
  },
  {
    id: 'neon-romance',
    title: 'Neon Romance',
    overview: 'Under the dazzling glow of Tokyo\'s skyscraper district, a private investigator and a street artist find themselves caught in a high-stakes conspiracy that tests their loyalties and love.',
    backdropUrl: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    rating: 'TV-14',
    duration: '2h 02m',
    releaseYear: 2026,
    genres: ['Drama', 'Romance', 'Thriller'],
    cast: ['Sonoya Mizuno', 'Dev Patel', 'Rinko Kikuchi'],
    matchScore: 93,
    isTrending: true,
    isPopular: false,
  },
  {
    id: 'crown-eldoria',
    title: 'The Crown of Eldoria',
    overview: 'Two siblings go on a quest through a magical, ancient forest to find the lost Crown of Eldoria and restore peace and harmony to their village before winter closes in.',
    backdropUrl: 'https://images.unsplash.com/photo-1519074002996-a69e7ac46a42?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519074002996-a69e7ac46a42?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    rating: 'G',
    duration: '1h 35m',
    releaseYear: 2024,
    genres: ['Fantasy', 'Adventure', 'Kids & Family'],
    cast: ['Mckenna Grace', 'Jacob Tremblay', 'Tom Hiddleston'],
    matchScore: 90,
    isTrending: false,
    isKids: true,
    isPopular: false,
  },
  {
    id: 'glacial-survival',
    title: 'Glacial Survival',
    overview: 'After their exploration plane crashes on a vast Greenland glacier, a team of climate scientists must rely on raw instincts to cross hundreds of miles of freezing sub-zero wilderness.',
    backdropUrl: 'https://images.unsplash.com/photo-1482862549707-f63cb32c5fd9?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1482862549707-f63cb32c5fd9?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    rating: 'PG-13',
    duration: '2h 08m',
    releaseYear: 2024,
    genres: ['Action', 'Adventure', 'Thriller'],
    cast: ['Mads Mikkelsen', 'Jessica Henwick', 'Yahya Abdul-Mateen II'],
    matchScore: 89,
    isTrending: false,
    isPopular: false,
  },
  {
    id: 'comedy-showcase',
    title: 'Comedy Central Showcase',
    overview: 'A brilliant lineup of world-class stand-up comedians perform a hilarious night of sharp, original, and deeply witty observations on modern lifestyle, tech, and relationships.',
    backdropUrl: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=1200&auto=format&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?w=400&auto=format&fit=crop',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    rating: 'TV-MA',
    duration: '1h 15m',
    releaseYear: 2025,
    genres: ['Comedy'],
    cast: ['Ali Wong', 'Sebastian Maniscalco', 'John Mulaney'],
    matchScore: 94,
    isTrending: false,
    isPopular: true,
  }
];

